# Generated by CMake, DO NOT EDIT
/Users/allomov/work/cpp_craft_0314/solutions/allomov/1/xcode_proj/CMakeFiles/cmake.check_cache: \
/Users/allomov/work/cpp_craft_0314/solutions/allomov/1/sources/1_3/CMakeLists.txt
	/usr/local/Cellar/cmake/2.8.12.2/bin/cmake -H/Users/allomov/work/cpp_craft_0314/solutions/allomov/1 -B/Users/allomov/work/cpp_craft_0314/solutions/allomov/1/xcode_proj
